services:
  - type: web
    name: ztan-backend
    runtime: node
    plan: free

    buildCommand: pnpm install && pnpm --filter=!@packages/business -r build && pnpm db:push
    startCommand: pnpm --filter @apps/core-api start

    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"

      - key: DATABASE_URL
        fromDatabase:
          name: ztan-db
          property: connectionString

      - key: USE_REAL_SIGNALS
        value: "false"

      - key: INTERNAL_SERVICE_TOKEN
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
