import { createRouteHandlerClient } from '@libs/supabase';
import { cookies } from 'next/headers';
import { NextRequest, NextResponse } from 'next/server';
import { Octokit } from 'octokit';
import { projectService } from '@libs/utils/server';
import { RateLimiter } from '@libs/utils/server';
import { withObservability, ApiHandler } from '@libs/utils/server';
import { logger } from '@libs/utils/server';

async function handler(req: NextRequest) {
    try {
        const body = await req.json();
        const { projectId, repoName, isPrivate } = body;

        if (!projectId || !repoName) {
            return NextResponse.json({ error: 'Project ID and Repository Name are required' }, { status: 400 });
        }

        const supabase = createRouteHandlerClient({ cookies });
        const { data: { session } } = await supabase.auth.getSession();

        if (!session) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const userId = session.user.id;
        const providerToken = session.provider_token;
        if (!providerToken) {
            return NextResponse.json({ error: 'GitHub Provider Token missing. Please log in with GitHub again.' }, { status: 400 });
        }

        // Fetch user profile for tiered rate limiting
        const { data: profile } = await supabase
            .from('user_profiles')
            .select('membership, role')
            .eq('id', userId)
            .single();

        const isPro = session.user.app_metadata?.plan === 'pro' || profile?.membership === 'pro' || profile?.role === 'owner';

        // Apply GitHub Push Rate Limiting (Free: 1/hr, Pro: 5/hr)
        const rateLimit = await RateLimiter.checkGithubLimit(userId, isPro);
        if (!rateLimit.allowed) {
            logger.warn({ userId, isPro }, 'GitHub rate limit exceeded');
            return NextResponse.json({
                error: isPro ? 'Too many repository creation requests.' : 'GitHub push limit reached (1/hr for free users). Upgrade to Pro for more.',
                retryAfter: rateLimit.retryAfter
            }, {
                status: 429,
                headers: { 'Retry-After': (rateLimit.retryAfter || 60).toString() }
            });
        }

        // Project ownership & status checks
        const isOwner = await projectService.verifyProjectOwnership(projectId, userId, supabase);
        if (!isOwner) {
            logger.error({ userId, projectId }, 'Ownership verification failed for GitHub push');
            return NextResponse.json({ error: 'Forbidden or Project not found' }, { status: 403 });
        }

        const project = await projectService.getProject(projectId, supabase);
        if (!project || project.status !== 'completed') {
            return NextResponse.json({ error: 'Project must be completed to push' }, { status: 400 });
        }

        const files = await projectService.getProjectFiles(projectId);
        if (!files || files.length === 0) {
            return NextResponse.json({ error: 'No files to push' }, { status: 400 });
        }

        const rlog = logger.child({ userId, projectId, repoName });
        rlog.info('Initiating GitHub repository creation');

        const octokit = new Octokit({ auth: providerToken });
        const { data: user } = await octokit.rest.users.getAuthenticated();

        const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
            name: repoName,
            private: isPrivate !== undefined ? isPrivate : false,
            description: project.description || 'Generated by MultiAgent',
            auto_init: true
        });

        rlog.info({ repoUrl: repo.html_url }, 'Repository created, starting file upload');

        const tree = [];
        for (const file of files) {
            const { data: blob } = await octokit.rest.git.createBlob({
                owner: user.login,
                repo: repo.name,
                content: Buffer.from(file.content || '').toString('base64'),
                encoding: 'base64'
            });

            tree.push({
                path: file.path,
                mode: '100644' as const,
                type: 'blob' as const,
                sha: blob.sha
            });
        }

        const { data: ref } = await octokit.rest.git.getRef({
            owner: user.login,
            repo: repo.name,
            ref: 'heads/main'
        });
        const currentSha = ref.object.sha;

        const { data: newTree } = await octokit.rest.git.createTree({
            owner: user.login,
            repo: repo.name,
            tree,
            base_tree: currentSha
        });

        const { data: commit } = await octokit.rest.git.createCommit({
            owner: user.login,
            repo: repo.name,
            message: 'feat: initial commit from MultiAgent 🚀',
            tree: newTree.sha,
            parents: [currentSha]
        });

        await octokit.rest.git.updateRef({
            owner: user.login,
            repo: repo.name,
            ref: 'heads/main',
            sha: commit.sha
        });

        rlog.info({ commitSha: commit.sha }, 'GitHub push successful');
        return NextResponse.json({ success: true, url: repo.html_url }, { status: 200 });

    } catch (error: unknown) {
        const err = error as { message?: string; stack?: string };
        logger.error({ error: err.message, stack: err.stack }, 'GitHub Push Error');
        throw error;
    }
}

export const POST = withObservability(handler as unknown as ApiHandler);

export const dynamic = 'force-dynamic';
