import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';
import { projectService } from '@packages/utils';
import { createRouteHandlerClient } from '@packages/supabase';
import { cookies } from 'next/headers';
import { RateLimiter } from '@packages/utils';

export async function GET(
    req: NextRequest,
    { params }: { params: { id: string } }
) {
    try {
        const projectId = params.id;

        if (!projectId) {
            return NextResponse.json({ error: 'Project ID is required' }, { status: 400 });
        }

        const supabase = createRouteHandlerClient({ cookies });
        const { data: { session } } = await supabase.auth.getSession();

        if (!session) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        // Apply Export Rate Limiting (10/hr)
        const rateLimit = await RateLimiter.checkExportLimit(session.user.id);
        if (!rateLimit.allowed) {
            return NextResponse.json({
                error: 'Too many export requests. Please try again later.',
                retryAfter: rateLimit.retryAfter
            }, {
                status: 429,
                headers: { 'Retry-After': (rateLimit.retryAfter || 60).toString() }
            });
        }

        // Verify Project Ownership via unified helper
        const isOwner = await projectService.verifyProjectOwnership(projectId, session.user.id, supabase);
        if (!isOwner) {
            return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
        }

        // Fetch the project to validate status
        const project = await projectService.getProject(projectId, supabase);

        if (!project) {
            return NextResponse.json({ error: 'Project not found' }, { status: 404 });
        }

        if (project.status !== 'completed') {
            return NextResponse.json({ error: 'Project must be completed to export' }, { status: 400 });
        }

        // Fetch the generated files from the database or DB service
        let files: { path: string; content: string }[] = [];
        const dbFiles = await projectService.getProjectFiles(projectId);
        if (dbFiles) {
            files = dbFiles.map(f => ({ path: f.path, content: f.content || '' }));
        }

        if (!files || files.length === 0) {
            console.warn(`[Export API] No files found for project ${projectId}. Triggering self-healing watchdog and returning fallback...`);

            files = [
                { path: 'package.json', content: '{\n  "name": "multiagent-project",\n  "version": "1.0.0",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build",\n    "start": "next start"\n  },\n  "dependencies": {\n    "next": "14.2.3",\n    "react": "18.3.1",\n    "react-dom": "18.3.1",\n    "tailwindcss": "3.4.3"\n  }\n}' },
                { path: 'next.config.js', content: '/** @type {import("next").NextConfig} */\nconst nextConfig = {};\nmodule.exports = nextConfig;' },
                { path: 'tailwind.config.js', content: '/** @type {import("tailwindcss").Config} */\nmodule.exports = { content: ["./pages/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}", "./app/**/*.{js,ts,jsx,tsx,mdx}"], theme: {}, plugins: [] };' },
                { path: 'app/page.tsx', content: 'import Header from "@components/Header";\nexport default function Home() { return <main><Header /><div className="p-8">Auto-generated Fallback Project. Generating...</div></main>; }' },
                { path: 'pages/api/health.ts', content: 'export default function handler(req: any, res: any) { res.status(200).json({ status: "healthy" }); }' },
                { path: 'components/Header.tsx', content: 'export default function Header() { return <header className="p-4 bg-gray-100">MultiAgent System</header>; }' },
                { path: 'styles/globals.css', content: '@tailwind base;\n@tailwind components;\n@tailwind utilities;' },
                { path: 'README.md', content: '# MultiAgent Project\nFallback generated by Export Watchdog because original files were missing. A rebuild has been queued.' }
            ] as { path: string; content: string }[];

            // Trigger internal rebuild fetch without awaiting
            fetch(`${req.nextUrl.origin}/api/generate-project`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Cookie': req.headers.get('cookie') || ''
                },
                body: JSON.stringify({
                    projectId: projectId,
                    executionId: 'exec-watchdog-' + Date.now(),
                    prompt: project.description || "A modern web application"
                })
            }).catch(e => console.error('Watchdog rebuild failed to trigger', e));
        }

        // Initialize JSZip
        const zip = new JSZip();

        // 1. Add all project files into the ZIP
        files.forEach((file) => {
            // JSZip handles nested folders automatically from paths (e.g. `src/components/App.tsx`)
            zip.file(file.path, file.content || '');
        });

        // 2. Add metadata.json for traceability
        const metadata = {
            projectId: project.id,
            executionId: project.last_execution_id,
            stackConfig: project.description, // Keeping prompt/stack config
            timestamp: new Date().toISOString(),
            status: project.status
        };
        zip.file('metadata.json', JSON.stringify(metadata, null, 2));

        // 3. Generate the ZIP as a buffer
        const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });

        // 4. Return as downloadable ZIP stream
        const response = new NextResponse(zipBuffer as unknown as BodyInit, {
            status: 200,
            headers: {
                'Content-Type': 'application/zip',
                'Content-Disposition': `attachment; filename="project-${projectId}.zip"`,
                'Content-Length': zipBuffer.length.toString(),
            },
        });

        return response;

    } catch (error) {
        console.error('ZIP Export Error:', error);
        return NextResponse.json({
            error: error instanceof Error ? error.message : 'Unknown error during export'
        }, { status: 500 });
    }
}
