import * as fs from 'fs';
import * as os from 'os';
import { execFileSync } from 'child_process';

export interface Tpm2PcrSelection {
    algorithm: 'sha256' | 'sha1';
    pcrs: number[];
}

export interface Tpm2QuotePayload {
    quoteBytes: string; // Base64 attested quote
    signatureBytes: string; // Base64 AK signature
    pcrs: { [pcrIndex: number]: string }; // Hex digests
}

export interface MeasuredBootEvent {
    pcrIndex: number;
    eventType: number;
    digest: string; // Hex string representation
    eventSize: number;
    eventData: string; // Hex or ASCII representation
}

export class PhysicalTpmConnector {
    private static TPM_DEVICE_PATH = '/dev/tpm0';
    private static BIOS_MEASUREMENT_PATH = '/sys/kernel/security/tpm0/binary_bios_measurements';

    static isHardwareTpmAvailable(): boolean {
        if (os.platform() !== 'linux') return false;
        try {
            return fs.existsSync(this.TPM_DEVICE_PATH);
        } catch {
            return false;
        }
    }

    // Helper: Execute a command mapping securely with stdout handling
    private static runCommand(binary: string, args: string[]): string {
        try {
            return execFileSync(binary, args, { stdio: 'pipe', encoding: 'utf8' }).trim();
        } catch (err: unknown) {
            const message = err instanceof Error ? err.message : String(err);
            throw new Error(`TPM_CMD_FAILURE: ${message}`);
        }
    }

    static generateEndorsementKey(_ekHandle: string = '0x81010001'): string {
        if (!this.isHardwareTpmAvailable()) {
            return 'MOCK_HARDWARE_EK_PUB_PEM';
        }
        return this.runCommand('tpm2_createek', ['--ek-context=ek.ctx', '--key-algorithm=rsa', '--public=ek.pub']);
    }

    static generateAttestationKey(_akHandle: string = '0x81010002'): string {
        if (!this.isHardwareTpmAvailable()) {
            return 'MOCK_HARDWARE_AK_PUB_PEM';
        }
        return this.runCommand('tpm2_createak', ['--ek-context=ek.ctx', '--ak-context=ak.ctx', '--public=ak.pub', '--private=ak.priv']);
    }

    static generatePhysicalQuote(nonceHex: string, pcrSelection: Tpm2PcrSelection): Tpm2QuotePayload {
        let useRealTpm = this.isHardwareTpmAvailable();
        if (useRealTpm) {
            try {
                const binary = os.platform() === 'win32' ? 'where' : 'which';
                execFileSync(binary, ['tpm2_quote'], { stdio: 'ignore' });
            } catch {
                useRealTpm = false;
            }
        }

        if (!useRealTpm) {
            if (process.env.ZTAN_MOCK_TPM === 'true' || process.env.VITEST) {
                const pcrs: { [pcrIndex: number]: string } = {};
                for (const pcr of pcrSelection.pcrs) {
                    pcrs[pcr] = '0000000000000000000000000000000000000000000000000000000000000000';
                }
                return {
                    quoteBytes: Buffer.from('MOCK_PHYSICAL_QUOTE').toString('base64'),
                    signatureBytes: Buffer.from('MOCK_PHYSICAL_SIGNATURE').toString('base64'),
                    pcrs
                };
            }
            throw new Error('HARDWARE_TPM_REQUIRED: /dev/tpm0 is absent. Gate C execution cannot fall back to simulated quotes.');
        }

        const pcrListStr = pcrSelection.pcrs.join(',');
        this.runCommand('tpm2_quote', [
            '--ak-context=ak.ctx',
            `--pcr-list=${pcrSelection.algorithm}:${pcrListStr}`,
            `--qualification=${nonceHex}`,
            '--message=quote.dat',
            '--signature=sig.dat'
        ]);

        // Read command artifacts
        const quoteBytes = fs.readFileSync('quote.dat').toString('base64');
        const signatureBytes = fs.readFileSync('sig.dat').toString('base64');

        // Parse actual PCRs generated by quote
        const pcrs: { [pcrIndex: number]: string } = {};
        for (const pcr of pcrSelection.pcrs) {
            const val = this.runCommand('tpm2_pcrread', [`${pcrSelection.algorithm}:${pcr}`]).trim();
            pcrs[pcr] = val;
        }

        return { quoteBytes, signatureBytes, pcrs };
    }

    // Command mapping for tpm2_checkquote (Verifying physical quote signature)
    static verifyPhysicalQuote(nonceHex: string, quoteBytesBase64: string, signatureBytesBase64: string): boolean {
        let useRealTpm = this.isHardwareTpmAvailable();
        if (useRealTpm) {
            try {
                const binary = os.platform() === 'win32' ? 'where' : 'which';
                execFileSync(binary, ['tpm2_checkquote'], { stdio: 'ignore' });
            } catch {
                useRealTpm = false;
            }
        }

        if (!useRealTpm) {
            if (process.env.ZTAN_MOCK_TPM === 'true' || process.env.VITEST) {
                return true;
            }
            throw new Error('HARDWARE_TPM_REQUIRED: /dev/tpm0 is absent. Cannot verify physical hardware quote.');
        }

        fs.writeFileSync('quote_verify.dat', new Uint8Array(Buffer.from(quoteBytesBase64, 'base64')));
        fs.writeFileSync('sig_verify.dat', new Uint8Array(Buffer.from(signatureBytesBase64, 'base64')));

        try {
            this.runCommand('tpm2_checkquote', [
                '--public=ak.pub',
                `--qualification=${nonceHex}`,
                '--message=quote_verify.dat',
                '--signature=sig_verify.dat'
            ]);
            return true;
        } catch {
            return false;
        }
    }

    // Native Measured Boot parsing from binary_bios_measurements
    static parseMeasuredBootEvents(): MeasuredBootEvent[] {
        const events: MeasuredBootEvent[] = [];
        
        if (!os.platform().startsWith('linux') || !fs.existsSync(this.BIOS_MEASUREMENT_PATH)) {
            // Simulated measured boot events (reconstructed event log)
            return [
                {
                    pcrIndex: 0,
                    eventType: 1, // EV_POST_CODE
                    digest: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
                    eventSize: 32,
                    eventData: 'BIOS_STARTUP_POST_MEASUREMENT'
                },
                {
                    pcrIndex: 4,
                    eventType: 4, // EV_ACTION
                    digest: 'ec0e804f3db6b5b2c7e0c4e7a2b255ea0b15c9a417537b02b0c15d7f12e84860',
                    eventSize: 16,
                    eventData: 'BOOT_LOADER_STAGE1'
                }
            ];
        }

        try {
            const buffer = fs.readFileSync(this.BIOS_MEASUREMENT_PATH);
            let offset = 0;

            // Simple event log parsing loop based on TCG specification format:
            // 4 bytes: PCR Index
            // 4 bytes: Event Type
            // 20 bytes (for SHA-1 event log) or digest structure: Digest
            // 4 bytes: Event Data Size
            // N bytes: Event Data
            while (offset + 32 <= buffer.length) {
                const pcrIndex = buffer.readUInt32LE(offset);
                const eventType = buffer.readUInt32LE(offset + 4);
                
                // Assuming standard SHA-1/SHA-256 event log digest structure size
                const digest = buffer.toString('hex', offset + 8, offset + 28);
                
                const eventSize = buffer.readUInt32LE(offset + 28);
                if (offset + 32 + eventSize > buffer.length) break;

                const eventData = buffer.toString('utf8', offset + 32, offset + 32 + eventSize);
                
                events.push({
                    pcrIndex,
                    eventType,
                    digest,
                    eventSize,
                    eventData
                });

                offset += 32 + eventSize;
            }
        } catch {
            // fallback
        }

        return events;
    }
}
