import * as fs from 'fs';
import * as os from 'os';
import { execSync } from 'child_process';

export interface Tpm2PcrSelection {
    algorithm: 'sha256' | 'sha1';
    pcrs: number[];
}

export interface Tpm2QuotePayload {
    quoteBytes: string; // Base64 attested quote
    signatureBytes: string; // Base64 AK signature
    pcrs: { [pcrIndex: number]: string }; // Hex digests
}

export interface MeasuredBootEvent {
    pcrIndex: number;
    eventType: number;
    digest: string; // Hex string representation
    eventSize: number;
    eventData: string; // Hex or ASCII representation
}

export class PhysicalTpmConnector {
    private static TPM_DEVICE_PATH = '/dev/tpm0';
    private static BIOS_MEASUREMENT_PATH = '/sys/kernel/security/tpm0/binary_bios_measurements';

    static isHardwareTpmAvailable(): boolean {
        if (os.platform() !== 'linux') return false;
        try {
            return fs.existsSync(this.TPM_DEVICE_PATH);
        } catch {
            return false;
        }
    }

    // Helper: Execute a command mapping securely with stdout handling
    private static runCommand(cmd: string): string {
        try {
            return execSync(cmd, { stdio: 'pipe' }).toString();
        } catch (err: any) {
            throw new Error(`TPM_CMD_FAILURE: ${err.message}`);
        }
    }

    // Command mapping for tpm2_createek (Endorsement Key generation)
    static generateEndorsementKey(ekHandle: string = '0x81010001'): string {
        if (!this.isHardwareTpmAvailable()) {
            return 'MOCK_HARDWARE_EK_PUB_PEM';
        }
        const cmd = `tpm2_createek --ek-context=ek.ctx --key-algorithm=rsa --public=ek.pub`;
        return this.runCommand(cmd);
    }

    // Command mapping for tpm2_createak (Attestation Key generation bound to EK)
    static generateAttestationKey(akHandle: string = '0x81010002'): string {
        if (!this.isHardwareTpmAvailable()) {
            return 'MOCK_HARDWARE_AK_PUB_PEM';
        }
        const cmd = `tpm2_createak --ek-context=ek.ctx --ak-context=ak.ctx --public=ak.pub --private=ak.priv`;
        return this.runCommand(cmd);
    }

    // Command mapping for tpm2_quote (Signing PCR state with AK)
    static generatePhysicalQuote(nonceHex: string, pcrSelection: Tpm2PcrSelection): Tpm2QuotePayload {
        let useRealTpm = this.isHardwareTpmAvailable();
        if (useRealTpm) {
            try {
                const cmd = os.platform() === 'win32' ? 'where tpm2_quote' : 'which tpm2_quote';
                execSync(cmd, { stdio: 'ignore' });
            } catch {
                useRealTpm = false;
            }
        }

        if (!useRealTpm) {
            // Simulated physical hardware TPM response
            return {
                quoteBytes: Buffer.from(`SIMULATED_PHYSICAL_QUOTE_NONCE_${nonceHex}`).toString('base64'),
                signatureBytes: Buffer.from(`SIMULATED_PHYSICAL_AK_SIG`).toString('base64'),
                pcrs: {
                    0: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
                    1: '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
                    7: 'fdeca12938475610fdeca12938475610fdeca12938475610fdeca12938475610'
                }
            };
        }

        const pcrListStr = pcrSelection.pcrs.join(',');
        const cmd = `tpm2_quote --ak-context=ak.ctx --pcr-list=${pcrSelection.algorithm}:${pcrListStr} --qualification=${nonceHex} --message=quote.dat --signature=sig.dat`;
        this.runCommand(cmd);

        // Read command artifacts
        const quoteBytes = fs.readFileSync('quote.dat').toString('base64');
        const signatureBytes = fs.readFileSync('sig.dat').toString('base64');

        // Parse actual PCRs generated by quote
        const pcrs: { [pcrIndex: number]: string } = {};
        for (const pcr of pcrSelection.pcrs) {
            const val = this.runCommand(`tpm2_pcrread ${pcrSelection.algorithm}:${pcr}`).trim();
            pcrs[pcr] = val;
        }

        return { quoteBytes, signatureBytes, pcrs };
    }

    // Native Measured Boot parsing from binary_bios_measurements
    static parseMeasuredBootEvents(): MeasuredBootEvent[] {
        const events: MeasuredBootEvent[] = [];
        
        if (!os.platform().startsWith('linux') || !fs.existsSync(this.BIOS_MEASUREMENT_PATH)) {
            // Simulated measured boot events (reconstructed event log)
            return [
                {
                    pcrIndex: 0,
                    eventType: 1, // EV_POST_CODE
                    digest: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
                    eventSize: 32,
                    eventData: 'BIOS_STARTUP_POST_MEASUREMENT'
                },
                {
                    pcrIndex: 4,
                    eventType: 4, // EV_ACTION
                    digest: 'ec0e804f3db6b5b2c7e0c4e7a2b255ea0b15c9a417537b02b0c15d7f12e84860',
                    eventSize: 16,
                    eventData: 'BOOT_LOADER_STAGE1'
                }
            ];
        }

        try {
            const buffer = fs.readFileSync(this.BIOS_MEASUREMENT_PATH);
            let offset = 0;

            // Simple event log parsing loop based on TCG specification format:
            // 4 bytes: PCR Index
            // 4 bytes: Event Type
            // 20 bytes (for SHA-1 event log) or digest structure: Digest
            // 4 bytes: Event Data Size
            // N bytes: Event Data
            while (offset + 32 <= buffer.length) {
                const pcrIndex = buffer.readUInt32LE(offset);
                const eventType = buffer.readUInt32LE(offset + 4);
                
                // Assuming standard SHA-1/SHA-256 event log digest structure size
                const digest = buffer.toString('hex', offset + 8, offset + 28);
                
                const eventSize = buffer.readUInt32LE(offset + 28);
                if (offset + 32 + eventSize > buffer.length) break;

                const eventData = buffer.toString('utf8', offset + 32, offset + 32 + eventSize);
                
                events.push({
                    pcrIndex,
                    eventType,
                    digest,
                    eventSize,
                    eventData
                });

                offset += 32 + eventSize;
            }
        } catch {
            // fallback
        }

        return events;
    }
}
