import * as crypto from 'crypto';
import { TpmEngine } from './tpm.js';
import type { TpmQuote } from './tpm.js';

export class QuarantineError extends Error {
    constructor(message: string) {
        super(message);
        this.name = 'QuarantineError';
    }
}

export class DetachedWitnessNode {
    private static readonly WITNESS_KEY = process.env.ZTAN_WITNESS_PRIVATE_KEY || crypto.randomBytes(32).toString('hex');

    private static expectedPcrs: Record<number, string> = {
        0: TpmEngine.BASELINE_PCR_0,
        7: TpmEngine.BASELINE_PCR_7,
        10: TpmEngine.BASELINE_PCR_10
    };

    // Active challenges list to track nonce state and prevent replay attacks
    private static activeChallenges: Set<string> = new Set();

    static configureExpectedPcrs(pcrs: Record<number, string>): void {
        this.expectedPcrs = { ...this.expectedPcrs, ...pcrs };
    }

    static generateChallenge(): string {
        const challenge = crypto.randomBytes(32).toString('hex');
        DetachedWitnessNode.activeChallenges.add(challenge);
        return challenge;
    }

    // Helper to manually add a mock active challenge for testing/replay simulations
    static registerActiveChallenge(challenge: string): void {
        DetachedWitnessNode.activeChallenges.add(challenge);
    }

    // Helper to clear active challenges for clean fuzzer resets
    static clearActiveChallenges(): void {
        DetachedWitnessNode.activeChallenges.clear();
    }

    /**
     * Out-of-band pre-flight integrity handshake verification and transactional co-signing.
     * @param proposalHash Hash of the proposed state transition
     * @param quote The TPM quote generated by the host daemon
     * @param challengeNonce The original challenge nonce issued by the witness
     * @returns Co-signing result
     */
    static requestCoSign(
        proposalHash: string,
        quote: TpmQuote,
        challengeNonce: string
    ): { signed: boolean; witnessSignature?: string; reason?: string } {
        // Enforce active challenge nonce constraint to block Nonce Replay Attacks
        if (!DetachedWitnessNode.activeChallenges.has(challengeNonce)) {
            return {
                signed: false,
                reason: 'QUOTE_NONCE_MISMATCH: The provided challenge nonce is invalid or has already been spent.'
            };
        }

        // Spend the nonce immediately to prevent future replay
        DetachedWitnessNode.activeChallenges.delete(challengeNonce);

        // Run TPM Remote Attestation verification
        const attestation = TpmEngine.verifyQuote(quote, challengeNonce, this.expectedPcrs);

        if (!attestation.verified) {
            if (attestation.errorType === 'HARD_QUARANTINE') {
                throw new QuarantineError(`HARD QUARANTINE: Host platform integrity compromised. Details: ${attestation.details}`);
            }
            if (attestation.errorType === 'DEGRADED_MODE') {
                return {
                    signed: false,
                    reason: `DEGRADED_MODE: Write capabilities suspended due to unverified binary execution. Details: ${attestation.details}`
                };
            }
            if (attestation.errorType === 'QUOTE_EXPIRED') {
                return {
                    signed: false,
                    reason: `QUOTE_EXPIRED: Stale attestation reused. Details: ${attestation.details}`
                };
            }
            if (attestation.errorType === 'SIGNATURE_INVALID') {
                return {
                    signed: false,
                    reason: `QUOTE_SIGNATURE_INVALID: Cryptographic verification of the quote signature or internal structure failed. Details: ${attestation.details}`
                };
            }
            if (attestation.errorType === 'NONCE_MISMATCH') {
                return {
                    signed: false,
                    reason: `QUOTE_NONCE_MISMATCH: Attestation nonce mismatch. Details: ${attestation.details}`
                };
            }
            // Other failures trigger Quarantine as fail-closed
            throw new QuarantineError(`VERIFICATION_FAILED: Attestation check failed. Details: ${attestation.details}`);
        }

        // Generate cryptographic witness co-signature using Witness Private Key
        const signature = crypto.createHmac('sha256', DetachedWitnessNode.WITNESS_KEY)
            .update(proposalHash + quote.signature)
            .digest('hex');

        return {
            signed: true,
            witnessSignature: `WITNESS_SIG_${signature}`
        };
    }
}
