import { defineConfig } from 'tsup';

export default defineConfig({
  format: ['cjs', 'esm'],
  dts: false,
  splitting: false,
  sourcemap: true,
  clean: true,
  target: 'node20',
  entry: ['index.ts'],
  external: [
    'bullmq',
    'ioredis',
    'pino',
    'uuid',
    'fs-extra',
    'archiver',
    'dotenv',
    'zod',
    'react',
    'stripe',
    'prom-client',
    'redlock',
    'next',
    'socket.io-client',
    '@supabase/supabase-js',
    '@temporalio/client',
    '@temporalio/worker',
    'axios',
    'express',
    'socket.io',
    'cors',
    'jsonwebtoken'
  ],
});
