import { ThresholdCrypto } from '../src/crypto-utils';
import { StabilityCircuit } from '../src/stability-circuit';
import { notaryService } from '../src/notary-service';

/**
 * INDEPENDENT AUDITOR CLI
 * 
 * This script demonstrates how a third-party auditor can verify the 
 * integrity of the ZTAN without trusting the main system.
 */
async function verifyAuditLog() {
    console.log('🔍 INDEPENDENT AUDIT START: Verifying simulated audit entry...');
    
    // Simulate an audit entry generated by the system
    const telemetry = { acc: 0.95, ldet: 50, lsla: 200, threshold: 0.85 };
    const payload = 'AUDIT_EVENT_001|PASS|node-a';
    
    const nodeIds = ['node-a', 'node-b', 'node-c'];
    const shares = await ThresholdCrypto.performDKG(nodeIds, 2);
    const groupPK = shares[0].groupPublicKey;
    
    const sigA = await ThresholdCrypto.signPartial(payload, shares[0].share, nodeIds[0], 2, nodeIds);
    const sigB = await ThresholdCrypto.signPartial(payload, shares[1].share, nodeIds[1], 2, nodeIds);
    const aggregate = await ThresholdCrypto.aggregate([sigA, sigB], 2, nodeIds);
    
    const zkProof = await StabilityCircuit.generateProof(telemetry.acc, telemetry.ldet, telemetry.lsla, telemetry.threshold);
    const anchor = await notaryService.notarize(payload);

    console.log('\n--- 1. Verifying Threshold Signature (BLS12-381) ---');
    if (aggregate) {
        const isSigValid = await ThresholdCrypto.verifyAggregate(aggregate, payload, groupPK, 2, nodeIds);
        console.log(isSigValid ? '✅ Signature Valid' : '❌ Signature INVALID');
    }

    console.log('\n--- 2. Verifying ZK-SNARK & Telemetry Binding (Poseidon) ---');
    const isZKValid = await StabilityCircuit.verifyProof(zkProof, telemetry.acc, telemetry.ldet, telemetry.lsla);
    console.log(isZKValid ? '✅ Proof & Binding Valid' : '❌ Proof INVALID');

    console.log('\n--- 3. Verifying WORM Anchor (S3 Object Lock) ---');
    const isAnchored = await notaryService.verify(payload, anchor.sequenceId);
    console.log(isAnchored ? '✅ Anchor Verified' : '❌ Anchor MISSING');

    if (aggregate && isZKValid && isAnchored) {
        console.log('\n🏆 FINAL AUDIT RESULT: COMPLIANT. System integrity verified.');
    } else {
        console.log('\n🚫 FINAL AUDIT RESULT: NON-COMPLIANT. Integrity violation detected.');
    }
}

verifyAuditLog().catch(console.error);
